name: AutoPEP8 Formatting

on:
  push:
    branches:
      - main

jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autopep8

    - name: Run autopep8
      run: |
        autopep8 --in-place --recursive --aggressive .

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -u
        git diff --quiet && git diff --staged --quiet || git commit -m "Apply autopep8 formatting"
    
    - name: Create Pull Request
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
        git push origin HEAD:formatting-changes
        gh pr create --base main --head formatting-changes --title "Apply autopep8 formatting" --body "Automated formatting changes" --repo ${{ github.repository }}
      env:
        MY_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

