name: Black Code Formatter

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Format code with Black
      run: |
        black .

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -u
        git diff --quiet && git diff --staged --quiet || git commit -m "Apply Black formatting"

    - name: Push changes
      run: |
        git push

    - name: Create Pull Request
      run: |
        gh auth login --with-token <${{ secrets.GITHUB_TOKEN }}
        git push origin HEAD:black-changes
        gh pr create --base main --head black-changes --title "Apply Black formatting" --body "Automated formatting changes" --repo ${{ github.repository }}

