name: Comment on issue or PR

on:
  issues:
    types: [labeled]
  pull_request_target:
    types: [labeled]

jobs:
  comment:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'thumbs up'
    steps:
    - name: Add comment
      uses: actions/github-script@v3
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "Thanks for your Thumbs Up :+1:! I appreciate it"
          });

