name: Auto Assign Reviewer

on:
  pull_request:
    types: [opened]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Assign a Reviewer
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prNumber = context.payload.pull_request.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const reviewers = ['your-github-username'];  // Add your GitHub username here
            
            await github.rest.pulls.requestReviewers({
              owner: owner,
              repo: repo,
              pull_number: prNumber,
              reviewers: reviewers
            });
