name: Twilio SMS Notification on Question Label

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'question'
    steps:
    - name: Send SMS using Twilio
      run: |
        curl -X POST https://api.twilio.com/2010-04-01/Accounts/$TWILIO_ACCOUNT_SID/Messages.json \
        --data-urlencode "To=$TARGET_PHONE_NUMBER" \
        --data-urlencode "From=$TWILIO_PHONE_NUMBER" \
        --data-urlencode "Body=Someone tagged an item with the 'question' label in your GitHub repository." \
        -u $TWILIO_ACCOUNT_SID:$TWILIO_AUTH_TOKEN
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
        TARGET_PHONE_NUMBER: ${{ secrets.TARGET_PHONE_NUMBER }}
